### ISSUE TITLE
[REQUEST] More configuration

### ISSUE THREAD

**Issue by AlexInABox** [RadSton/ZeitvertreibCommon#1]
I would like to be able to configure the following:
- Amount of projectiles launched by the custom items per second
- enabled/disable SCP-914 recepies
- random death chances when using Fake500

Please rework each command to only be used via RemoteAdmin.
When using a custom item command create a wrapper command so that no extra permissions outside of the scope of `zeitvertreib.team` have to be granted.

**Comment by radston12** [comment]
This plugin is "make max.bambus happy" and not "make production happy" but I will change that, at least I hope I will

Before I start implementing the config I wanted to ask if this config is detailed enough or if I missed something:
(also ignore the typos for now I know there are many)

```yml
is_enabled: true
debug: false

adminitems:
  grenader:
    # Grenades spawned per shot (must be an integer) (multiply by 60 for firerate per second)
    rate: 5
    # If true the grenades will explode on collision 
    explodeOnImpact: true
    # How much ammo the weapon uses per shot
    ammoPerShot: 0
    # If the weapon can be reloaded
    reloadable: false

    # Should a message be sent to AdminChat if this weapon is picked up
    #
    # Messages broadcasted when event is fired
    # Leave strings empty to disable messages
    # In formatting you can use:
    # {Name} -> Name of player
    # {Id} -> Id of player
    # {Room} -> Current room of player
    #
    # You can also use the SCP: SL default formating
    # like <color=#f00> </color> or <size=50></size>
    #
    # Important: "AdminChat" will send silently / without broadcast
    #            for a broadcast configure "AdminsBroadcast"  
    broadcasts:
      pickedUp:
        AdminChat: "{NAME}({ID}) picked up Grenader in {Room}"
        AdminsBroadcast: "{NAME} picked up Grenader"
        PlayerBroadcast: ""
        MapBroadcast: ""
      dropped: 
        AdminChat: "{NAME}({ID}) picked up Grenader in {Room}"
        AdminsBroadcast: "{NAME} dropped up Grenader"
        PlayerBroadcast: "<color=#f00>You dropped a dangerous weapon!</color>"
        MapBroadcast: ""
  blitzer:
    # SCP-2176 spawned per shot (must be an integer) (multiply by 60 for firerate per second)
    rate: 5
    # How much ammo the weapon uses per shot
    ammoPerShot: 0
    # If the weapon can be reloaded
    reloadable: false

    # Should a message be sent to AdminChat if this weapon is picked up
    #
    # Messages broadcasted when event is fired
    # Leave strings empty to disable messages
    # In formatting you can use:
    # {Name} -> Name of player
    # {Id} -> Id of player
    # {Room} -> Current room of player
    #
    # You can also use the SCP: SL default formating
    # like <color=#f00> </color> or <size=50></size>
    #
    # Important: "AdminChat" will send silently / without broadcast
    #            for a broadcast configure "AdminsBroadcast"  
    broadcasts:
      pickedUp:
        AdminChat: "{NAME}({ID}) picked up Blitzer in {Room}"
        AdminsBroadcast: "{NAME} picked up Blitzer"
        PlayerBroadcast: ""
        MapBroadcast: ""
      dropped: 
        AdminChat: "{NAME}({ID}) picked up Blitzer in {Room}"
        AdminsBroadcast: "{NAME} dropped up Blitzer"
        PlayerBroadcast: "<color=#f00>You dropped a dangerous weapon!</color>"
        MapBroadcast: ""
  fake500:

    # If the default Exiled.CustomItems text should be shown when item is picked up
    # This option is usless because it would reveal that it is no ordinary SCP-500
    showPickedUpExiledText: false

    # If the default Exiled.CustomItems text should be shown when item is selected from the inventory
    # This option is usless because it would reveal that it is no ordinary SCP-500
    showItemInfoExiledText: false
   
    # Effects given immediatly after consumtion
    effectsOnConsumtion:
      - effect: "AmnesiaVision"
        intensity: 10
        duration: 100
      - effect: "Blinded"
        intensity: 10
        duration: 100

    # Delay in seconds after the initial effects the death events take place
    delayBeforeDeathEvent: 2

    # Possible events are: 
    #
    # - "kick": Kicks player with message
    #    -> message: Kick message 
    #
    # - "tesla": Teleports player inbetween tesla gate
    #
    # - "effect": Applies effects to player
    #    -> effects:
    #         - effect: "Blinded"
    #           intensity: 10
    #           duration: 100
    #
    # - "hurt": Applies direct damage to player with custom death message
    #    -> damage: Integer of damage (capped at 65535)
    #    -> reason: Death reason string
    #
    # - "position": Adds defined values to the position of a player (f.e. tp 50 meters up)
    #    -> addedX: float that is added to the x coordinate of the player´s position vector
    #    -> addedY: float that is added to the y coordinate of the player´s position vector
    #    -> addedZ: float that is added to the z coordinate of the player´s position vector
    # 
    # - "explode": Makes the player explode (default explosion can damage surroundings) 
    #
    #
    # Chance is an Integer (Note that 0 will result in the event beeing disabled)
    # The higher "Chance" is the higher is the probability of it being executed 
    #
    # How to calculate percentage from chance:
    #   Sum up all chances from every deathEvent then inverse them (german: Kehrwert) (1 divided by <SUM OF CHANCES>) 
    #   multiply that value by the chance of the event you would like to get the percentage from
    #   and finally multiply again by 100 to get the final percent chance
    deathEvents:
      - event: "kick"
        chance: 1
        message: "Timed out"
      - event: "explode"
        chance: 1
      - event: "effect"
        chance: 1
        effects:
          - effect: "CardiacArrest"
            intensity: 1
            duration: 100
          - effect: "SeveredHands"
            intensity: 1
            duration: 1
      - event: "hurt"
        chance: 1
        damage: 65535
        reason: "You were bitten by Belu´s dog!"
      - event: "position"
        chance: 1
        addedX: 0
        addedY: 50
        addedZ: 0
      - event: "effect"
        chance: 1
        effects:
          - effect: "SeveredHands"
            intensity: 1
            duration: 1
      - event: "tesla"
        chance: 1
      - event: "effect"
        chance: 1
        effects:
          - effect: "CardiacArrest"
            intensity: 1
            duration: 100
          - effect: "Flashed"
            intensity: 1
            duration: 100
            # Ensnared -> Effect ID for Slowness
          - effect: "Ensnared"
            intensity: 100
            duration: 100

    # Should a message be sent to AdminChat if this weapon is picked up
    #
    # Messages broadcasted when event is fired
    # Leave strings empty to disable messages
    # In formatting you can use:
    # {Name} -> Name of player
    # {Id} -> Id of player
    # {Room} -> Current room of player
    #
    # You can also use the SCP: SL default formating
    # like <color=#f00> </color> or <size=50></size>
    #
    # Important: "AdminChat" will send silently / without broadcast
    #            for a broadcast configure "AdminsBroadcast"  
    broadcasts:
      pickedUp:
        AdminChat: ""
        AdminsBroadcast: ""
        PlayerBroadcast: ""
        MapBroadcast: ""
      dropped: 
        AdminChat: ""
        AdminsBroadcast: ""
        PlayerBroadcast: ""
        MapBroadcast: ""

scp914changes:
  # Possible values for knowSetting ´s are (Scp914.Scp914KnobSetting Enum): Rough, Coarse, OneToOne, Fine, VeryFine
  - knobSetting: "OneToOne"
    # Input can be any ItemType except None
    input: "KeycardMTFPrivate"
    # outputSuccess can be any ItemType that is given when the chance is on the players side
    outputSuccess: "KeycardContainmentEngineer"
    # outputFail can be any ItemType that is given when the chance is not met
    outputFail: "None"
    # Chance value here is a percentage from 1-100 !
    chance: 100
```

Yes this is a https://tenor.com/view/imostergolfra-gif-25274972
